### PR TITLE
Feature/prebuild database files

### PR DESCRIPTION
**Pull request by martingraf4**
Closing #63

### CODE REVIEW

**Comment by martingraf4** [comment]
@phpfs please review changes to `app`

**Review by Lasklu — APPROVED** [review]

**Comment by phpfs** [comment]
What's up with the CI files? :D @martingraf4

**Review by phpfs — APPROVED** [review]
Frontend changes approved

**Comment by martingraf4** [comment]
> What's up with the CI files? :D @martingraf4

A long running test in `wrapper` is only performed in CI environment (only via `npm run test-ci`, not `npm run test`. The many changes come from autoformat :D

**Pull request merged**
