### PR TITLE
Improve tooltip information on metrics

### LINKED ISSUE #28: Tooltips on metrics do not show up
Currently, the tooltip that should explain a metric does not work.

### LINKED ISSUE #40: Refactor Metrics description
- split "formula" and "information"
- make formula shorter (e.g. by using fractions and abbreviations)

### PR DESCRIPTION
**Pull request by phpfs**
Having some kind of documentation on metrics in-app will aid the understanding.

Closes #40
Closes #28

### CODE REVIEW

**Comment by phpfs** [comment]
@martingraf4 Can you do the refactoring described in #40 - or do we want to hold off on that until we really need to supply additional information? :)

**Comment by phpfs** [comment]
btw - should we include some kind of sorting order?
(precision/recall etc. should absolutely be on the first page of the carousel)

**Comment by martingraf4** [comment]
Will reorder the metrics and implement #40

**Comment by martingraf4** [comment]
@phpfs I have added optional `info` and `infoLink` attributes and renamed `description` -> `formula`. Please implement `info` and `infoLink` support.

Additionally for me the math expression is not properly rendered:

image

**Pull request merged**
